### ISSUE TITLE
The game crashes while loading the save

### ISSUE THREAD

**Issue by TwilightHome20** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#257]
## Essential Infomations
- Version of the game(2.31.0) : 
- [ No] Was your save created from previous version?
- [Yes] Did a crash occurs with the game?
- About The Bug : The game crashes when trying to loading a save
- Bug Occurrence Conditions : 
While trying to load the game save
## Optional Infomations
- Screenshot :
![Screenshot_2022-09-02-19-08-13-925_com miui bugreport](https://user-images.githubusercontent.com/101049847/188126974-9c9381ca-b03b-4f22-bcd1-e9c9325e8857.jpg)

The video 
  :https://v.superbed.cn/play/6311e2fe16f2c2beb110b81b

System log :
`java.lang.RuntimeException: fatal error occured while moving between floors. Seed:4427446625369 depth:-1
	at com.shatteredpixel.shatteredpixeldungeon.scenes.InterlevelScene.update(InterlevelScene.java:15)
	at com.watabou.noosa.Game.update(Game.java:9)
	at com.watabou.noosa.Game.step(Game.java:5)
	at com.watabou.noosa.Game.render(Game.java:15)
	at c.k.onDrawFrame(AndroidGraphics.java:39)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1577)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.shatteredpixel.shatteredpixeldungeon.actors.hero.Hero.pointsInTalent(com.shatteredpixel.shatteredpixeldungeon.actors.hero.Talent)' on a null object reference
	at com.shatteredpixel.shatteredpixeldungeon.actors.hero.Hero.isImmune(Hero.java:9)
	at com.shatteredpixel.shatteredpixeldungeon.actors.buffs.Buff.attachTo(Buff.java:1)
	at com.shatteredpixel.shatteredpixeldungeon.actors.buffs.Poison.attachTo(Poison.java:1)
	at com.shatteredpixel.shatteredpixeldungeon.actors.Char.restoreFromBundle(Char.java:6)
	at com.shatteredpixel.shatteredpixeldungeon.actors.hero.Hero.restoreFromBundle(Hero.java:4)
	at com.watabou.utils.Bundle.get(Bundle.java:8)
	at com.watabou.utils.Bundle.get(Bundle.java:9)
	at com.shatteredpixel.shatteredpixeldungeon.Dungeon.loadGame(Dungeon.java:46)
	at com.shatteredpixel.shatteredpixeldungeon.Dungeon.loadGame(Dungeon.java:1)
	at com.shatteredpixel.shatteredpixeldungeon.scenes.InterlevelScene.restore(InterlevelScene.java:3)
	at com.shatteredpixel.shatteredpixeldungeon.scenes.InterlevelScene.access$500(Unknown Source:0)
	at com.shatteredpixel.shatteredpixeldungeon.scenes.InterlevelScene$4.run(InterlevelScene.java:11)
`

**Comment by TwilightHome20** [comment]
Creating new save can still play normally

**Comment by Hoto-Mocha** [comment]
foxed in dev, so don't delete your save if u want to play that more.

**Comment by Hoto-Mocha** [comment]
fixed in v2.32.0.
