### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by KazenohaOwO** [Hoto-Mocha/Shattered-Pixel-Dungeon-Modding#312]
## Essential Infomations(Use English Please)
- Version of the game(Ex.2.41.0) : 
- [no ] Was your save created from previous version?
- [yes] Did a crash occurs with the game?
- About The Bug : The game crashed after use the ratmogrify on tank 
- Bug Occurrence Conditions : Use the ratmogrify on tank

## Optional Infomations
- Screenshot :No screenshots, but I have an Crash log
- 
- java.lang.NullPointerException: Attempt to read from field 'int com.shatteredpixel.shatteredpixeldungeon.actors.Char.pos' on a null object reference
	at com.shatteredpixel.shatteredpixeldungeon.actors.mobs.Tank.damageRoll(Tank.java:15)
	at com.shatteredpixel.shatteredpixeldungeon.actors.hero.abilities.Ratmogrify$TransmogRat.damageRoll(Ratmogrify.java:3)
	at com.shatteredpixel.shatteredpixeldungeon.actors.Char.attack(Char.java:51)
	at com.shatteredpixel.shatteredpixeldungeon.actors.Char.attack(Char.java:3)
	at com.shatteredpixel.shatteredpixeldungeon.actors.mobs.Mob.doAttack(Mob.java:22)
	at com.shatteredpixel.shatteredpixeldungeon.actors.mobs.Mob$Hunting.act(Mob.java:33)
	at com.shatteredpixel.shatteredpixeldungeon.actors.mobs.Mob.act(Mob.java:91)
	at com.shatteredpixel.shatteredpixeldungeon.actors.hero.abilities.Ratmogrify$TransmogRat.act(Ratmogrify.java:63)
	at com.shatteredpixel.shatteredpixeldungeon.actors.Actor.process(Actor.java:127)
	at com.shatteredpixel.shatteredpixeldungeon.scenes.GameScene$2.run(GameScene.java:1)

**Comment by KazenohaOwO** [comment]
![Screenshot_2023-03-19-16-55-04-969_com arrangedpixel arrangedpixeldungeon](https://user-images.githubusercontent.com/116419372/226164711-c7a41273-2be7-4d85-8f09-280e771c0886.jpg)
![Screenshot_2023-03-19-16-55-39-795_com arrangedpixel arrangedpixeldungeon](https://user-images.githubusercontent.com/116419372/226164715-55783356-afcb-4c68-b51f-c744fa99b7da.jpg)

**Comment by Hoto-Mocha** [comment]
I'll check in the next verson. thanks

**Comment by Hoto-Mocha** [comment]
It causes no error, but I fixed the code what you reported, and has chance to cause an error.
